PajtonPS/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GrbicPortal.urls')),

]

djangoProject/Portal/urls.py
from django.urls import path

from . import views

app_name= 'portal'

urlpatterns = [
    path('', views.index, name='index'),
    path('employees/', views.employees, name='employees'),
]

dms/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from dms import views
from dms.views import RootFolder, CreateFile, CreateFolder, UpdateFile, UpdateFolder, DeleteFile, DeleteFolder

urlpatterns = [
    path('', login_required(RootFolder.as_view()), name='dms'),
    path('create/', login_required(CreateFile.as_view()), name='create_file'),
    path('create_folder/', login_required(CreateFolder.as_view()), name='create_folder'),
    path('edit/<int:pk>', login_required(UpdateFile.as_view()), name='update_file'),
    path('edit_folder/<int:pk>', login_required(UpdateFolder.as_view()), name='update_folder'),
    path('delete/<int:pk>', login_required(DeleteFile.as_view()), name='delete_file'),
    path('delete_folder/<int:pk>', login_required(DeleteFolder.as_view()), name='delete_folder'),
    path('<str:name>/', views.get_files, name='dms'),
]

forum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),

]

employees/models.py
from django.db import models


# Create your models here.
class Employee(models.Model):
    name = models.CharField(max_length=35)
    surname = models.CharField(max_length=35)
    title = models.CharField(max_length=45)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return self.name + " " + self.surname

portal/index/models.py
from django.db import models

class Sector(models.Model):
    sector_name = models.CharField(max_length=50)

    def __str__(self):
        return self.sector_name

class Position(models.Model):
    position_name = models.CharField(max_length=50)
    sector_name = models.ForeignKey(Sector, on_delete=models.CASCADE)

    def __str__(self):
        return self.position_name

class Employee(models.Model):
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return (f" {self.first_name} {self.last_name}")

djangoProject/Portal/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def employees(request):
    return render(request, 'employees.html')

employees/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.template import loader

from .models import Employee
# Create your views here.
from django.urls import path

from . import views


def index(request):
    employees_list = Employee.objects.order_by('id')
    template = loader.get_template('employees/employees.html')
    context = {
        'employees_list': employees_list,
    }
    return HttpResponse(template.render(context, request))


def home_page(request):
    template = loader.get_template('employees/naslovna.html')
    return HttpResponse(template.render(None, request))

portal/index/views.py
from django.shortcuts import render

from django.views import generic
from . models import Employee

def index(request):
    return render(request, 'index/index.html')

class EmployeeView(generic.ListView):
    model = Employee
    template_name = 'index/employees.html'
    context_object_name = 'employee_list'

portal/templates/portal/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="icon" href="{% static 'portal/images/logo_header.png' %} #}" type="image/icon type">


        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- All custom CSS goes after Bootstrap CSS so you can override it -->
        <link rel="stylesheet" type="text/css" href="{% static 'portal/css/base.css' %}">


        <!-- Block for page title-->
        {% block title %}
        {% endblock %}

    </head>
    <body>
        <!-- Beginning of Nav bar-->
        <nav class="nav navbar navbar-dark navbar-expand-lg ">
            <a class="navbar-brand">
                <img src="{% static 'portal/images/logo_header.png' %}" width="63" height="36" alt="">Planet Soft
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link hover" href="">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:employees' %}">Employees</a>
                </li>
            </ul>
        </nav>
        <!-- End of Nav bar-->

        <!-- Block for page title-->
        {% block body %}
        {% endblock %}

         <!-- Beginning of Nav bar-->
        <footer>

        </footer>
        <!-- End of Nav bar-->

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <!-- Custom JS-->
    </body>
</html>

portal/templates/portal/employees.html
{% extends "portal/base.html" %}

{% block title %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portal/css/portalEmployees.css' %}">
    <title>Planet Soft Employees</title>
{% endblock %}

{% block body %}
    <h1 class="text-center">Meet the the team behind <span class="green">Planet Soft</span></h1>
      <div class="row">
          {% for employee in all_employees %}
                  <!-- Beginning of Card-->
                  <div class="col-sm">
                       <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">{{employee.first_name}} {{ employee.last_name }}</h5>
                            <div class="row">
                                <div class="col">
                                    <p class="card-text">{% lorem 50 w %}</p>
                                </div>
                                 <div class="col">
                                     <img src="{% static 'portal/images/logo_header.png' %}">
                                 </div>
                            </div>
                            <a href="#" class="btn btn-primary">Contact</a>
                          </div>
                       </div>
                  </div>
                  <!-- End of Card-->
              <!-- Change the number to edit how many cards are shown in one row-->
               {% if forloop.counter|divisibleby:4 %}
                   </div>
                   {% if forloop.counter < all_employees.count %}
                       <div class="row">
                   {% endif %}
              {% endif %}
          {% endfor %}
          </div>
{% endblock %}

portal/templates/portal/index.html
{% extends "portal/base.html" %}

{% block title %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portal/css/portalHome.css' %}">
    <title>Planet Soft</title>
{% endblock %}

{% block body %}
    <h1 class="text-center">Make your life easier with <span class="green">Planet Soft</span></h1>

    <div class="row">
        <div class="col">
        <p>{% lorem 150 w %}</p>

        </div>
        <div class="col">
            <img src="{% static 'portal/images/logo_header.png' %}"/>
        </div>
    </div>

{% endblock %}