GrbicPortal/urls.py
from django.urls import path

from . import views

app_name= 'GrbicPortal'

urlpatterns = [
    path('', views.index, name='indexData'),
    path('employees/', views.AllEmployeesListView.as_view(), name='employeesData'),
]

PajtonPS/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GrbicPortal.urls')),

]

dms/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from dms import views
from dms.views import RootFolder, CreateFile, CreateFolder, UpdateFile, UpdateFolder, DeleteFile, DeleteFolder

urlpatterns = [
    path('', login_required(RootFolder.as_view()), name='dms'),
    path('create/', login_required(CreateFile.as_view()), name='create_file'),
    path('create_folder/', login_required(CreateFolder.as_view()), name='create_folder'),
    path('edit/<int:pk>', login_required(UpdateFile.as_view()), name='update_file'),
    path('edit_folder/<int:pk>', login_required(UpdateFolder.as_view()), name='update_folder'),
    path('delete/<int:pk>', login_required(DeleteFile.as_view()), name='delete_file'),
    path('delete_folder/<int:pk>', login_required(DeleteFolder.as_view()), name='delete_folder'),
    path('<str:name>/', views.get_files, name='dms'),
]

forum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),

]

GrbicPortal/models.py
from django.db import models

class Employee(models.Model):
    employeeName = models.CharField(max_length=200)
    employeeDateOfJoining = models.CharField(max_length=200)
    employeeDepartment = models.CharField(max_length=500)
    employeeGender = models.BooleanField(default=False)
# Create your models here.

GrbicPortal/views.py
from django.shortcuts import render
from .models import Employee
from django.views.generic.list import ListView

# Create your views here.

def index(request):
    return render(request, 'GrbicPortal/indexData.html')


#def employees(request):
 #   employeeList = Employee.objects.all()
  #  return render(request, 'GrbicPortal/employeeData.html', {{"employeeList":employeeList}})
class AllEmployeesListView(ListView):
    model = Employee
    context_object_name = 'employeesList'
    template_name = 'GrbicPortal/employeeData.html'

GrbicPortal/templates/GrbicPortal/employeeData.html
{% extends 'GrbicPortal/index.html' %}

{% block body %}
      <div class="row">
          {% for employeeSingle in employeesList %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{employeeSingle.employeeName}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ employeeSingle.employeeDepartment }}</h6>
                        <p class="card-text">Date of joining: {{ employeeSingle.employeeDateOfJoining }}</p>
                        {% if employeeSingle.employeeGender %}
                            <p class="card-text">Gender: Female</p>
                        {% else %}
                            <p class="card-text">Gender: Male</p>
                        {% endif %}
                    </div>
                </div>

                  <!-- End of Card-->
              <!-- Change the number to edit how many cards are shown in one row-->
                 {% if forloop.counter|divisibleby:4 %}
                   </div>
                   {% if forloop.counter < all_employees.count %}
                       <div class="row">
                   {% endif %}
             {% endif %}
          {% endfor %}
          </div>
{% endblock %}

GrbicPortal/templates/GrbicPortal/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>PlanetSoft Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- All custom CSS goes after Bootstrap CSS so you can override it -->
        <style>
            body {
              margin: 0;
              font-family: Arial, Helvetica, sans-serif;
            }

            .column {
                float: left;
                width: 50%;
            }
            .navbar-navbar-default {
                position: fixed;
                top: 0;
                display: block;
            }

            #logo {
                margin-right: 10px;
                height: 50px;
                width:100px;
                float: right;
                display: block;
            }
            #imageContent{
                margin-right: 10px;
                height: 500px;
                width: 700px;
                float: right;
                display: block;
            }
    /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }
        </style>

    </head>
    <body>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" id="naslov">Planet Soft</a>
                </div>
                <ul class="nav fixed-top navbar-nav">
                    <li><a href="{% url 'GrbicPortal:indexData' %}">Home</a></li>
                    <li><a href="{% url 'GrbicPortal:employeesData' %}">Employees</a></li>
                </ul>
                <img id="logo" src="https://planetsoft.ba/images/logo_header.png">
            </div>
       </nav>


        {% block body %}
        {% endblock %}


    </body>
</html>

GrbicPortal/templates/GrbicPortal/indexData.html
{% extends 'GrbicPortal/index.html' %}

{% block body %}
     <div class="row" style="padding:20px;margin-top:50px;background-color:#919090;height:1500px;">
            <div class="column">
                <h1>What is Lorem Ipsum?</h1>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
                    the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
                    scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
                    electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
                    Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
                    PageMaker including versions of Lorem Ipsum</p>
            </div>
            <div class="column">
                <img id="imageContent" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallpapercave.com%2Fwp%2Fwp3855114.jpg&f=1&nofb=1">
            </div>
     </div>

{% endblock %}