PajtonPS/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GrbicPortal.urls')),

]

dms/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from dms import views
from dms.views import RootFolder, CreateFile, CreateFolder, UpdateFile, UpdateFolder, DeleteFile, DeleteFolder

urlpatterns = [
    path('', login_required(RootFolder.as_view()), name='dms'),
    path('create/', login_required(CreateFile.as_view()), name='create_file'),
    path('create_folder/', login_required(CreateFolder.as_view()), name='create_folder'),
    path('edit/<int:pk>', login_required(UpdateFile.as_view()), name='update_file'),
    path('edit_folder/<int:pk>', login_required(UpdateFolder.as_view()), name='update_folder'),
    path('delete/<int:pk>', login_required(DeleteFile.as_view()), name='delete_file'),
    path('delete_folder/<int:pk>', login_required(DeleteFolder.as_view()), name='delete_folder'),
    path('<str:name>/', views.get_files, name='dms'),
]

events/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from events.views import EventCreate, EventUpdate, EventDelete, DayDetails, CalendarView, EventPreview

urlpatterns = [
    path('', login_required(CalendarView.as_view()), name='calendar'),
    path('<int:year>/<int:month>', login_required(CalendarView.as_view()), name='specific-month-calendar'),
    path('create/', login_required(EventCreate.as_view()), name='event-create'),
    path('<int:pk>/', login_required(EventUpdate.as_view()), name='event-edit'),
    path('preview/<int:pk>/', login_required(EventPreview.as_view()), name='event-preview'),
    path('delete/<int:pk>/', login_required(EventDelete.as_view()), name='event-delete'),
    path('events/<int:year>/<int:month>/<int:day>', login_required(DayDetails.as_view()), name='day-events'),
]

forum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),

]

events/models.py
from django.db import models

from events.constants import EVENT_TYPES


class Event(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    creation_date = models.DateField(auto_now_add=True)
    edited_date = models.DateField(auto_now=True)
    shared = models.ManyToManyField(to='users.User', related_name='shared')
    title = models.CharField(max_length=48)
    details = models.CharField(max_length=256, null=True, blank=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    repeat_days = models.IntegerField(default=0, null=True, blank=True)
    repeat_every_year = models.BooleanField(default=False)
    type = models.CharField(max_length=20, null=True, blank=True, choices=EVENT_TYPES)

events/forms.py
from datetime import datetime

from django import forms

from events.constants import LABEL_TEXT_EVENT
from events.models import Event
from users.models import User


class CreateEvent(forms.ModelForm):
    use_required_attribute = False
    field_order = ['title', 'details', 'start_time', 'end_time', 'repeat_days', 'repeat_every_year']
    shared = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=User.objects.all(),
                                            required=False)
    start_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(date_attrs={'type': 'date'},
                                                                           time_attrs={'type': 'time'}))
    end_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(date_attrs={'type': 'date'},
                                                                         time_attrs={'type': 'time'}))

    class Meta:
        model = Event
        fields = {'title', 'details', 'shared', 'type', 'start_time', 'end_time', 'repeat_days', 'repeat_every_year'}

    def save(self, commit=True):
        event = super(CreateEvent, self).save(commit=True)
        # todo ovdje implementirati task scheduler na osnovu odabranog unosa
        if commit:
            event.save()
        return event

    def clean_start_time(self):
        data = self.cleaned_data['start_time']
        if data and data < datetime.now():
            raise forms.ValidationError('Događaj ne može počinjati u prošlosti')
        return data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in LABEL_TEXT_EVENT.items():
            self.fields[key].label = value

events/views.py
from datetime import date, datetime, timedelta

from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView

from events.constants import MONTHS, JANUARY, DECEMBER, PREVIOUS, NEXT
from events.forms import CreateEvent
from events.models import Event
from events.utils import Calendar
from praksaPlanetSoft.constants import HTTP_STATUS_400
from users.models import User


class CalendarView(ListView):
    model = Event
    template_name = 'events/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar if not provided
        if ('year' and 'month' in self.kwargs) and (self.kwargs['month'] and self.kwargs['year']) > 0:
            d = date(self.kwargs['year'], self.kwargs['month'], day=1)
        else:
            d = datetime.today()

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.format_month(self.request.user)
        context['year'] = d.year
        context['next_year'] = d.year + NEXT
        context['previous_year'] = d.year - PREVIOUS
        context['month'] = d.month

        if d.month == JANUARY:
            context['next_month'] = d.month + NEXT
            context['previous_month'] = DECEMBER
        elif d.month == DECEMBER:
            context['next_month'] = JANUARY
            context['previous_month'] = d.month - PREVIOUS
        else:
            context['next_month'] = d.month + NEXT
            context['previous_month'] = d.month - PREVIOUS

        context['months'] = MONTHS
        context['selected_month'] = MONTHS[d.month - PREVIOUS]
        context['calendar'] = mark_safe(html_cal)
        return context


class EventCreate(CreateView):
    model = Event
    template_name = 'events/event.html'
    success_url = '/calendar/'
    form_class = CreateEvent

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['shared'].queryset = User.objects.exclude(id=self.request.user.id)
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = HTTP_STATUS_400
        return response


class EventUpdate(UpdateView):
    model = Event
    template_name = 'events/event-edit.html'
    success_url = '/calendar/'
    form_class = CreateEvent

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['shared'].queryset = User.objects.exclude(id=self.request.user.id)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CreateEvent(instance=context['object'])
        return context

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = HTTP_STATUS_400
        return response


class EventPreview(DetailView):
    model = Event
    template_name = 'events/event-preview.html'


class EventDelete(UserPassesTestMixin, DeleteView):
    model = Event
    success_url = '/calendar/'
    template_name = 'events/event-confirm-deletion.html'

    def test_func(self):
        if self.request.user.is_admin or self.request.user.is_superuser or \
                self.request.user == Event.objects.filter(id=self.kwargs['pk']).get().author:
            return True
        elif self.request.user.is_authenticated:
            raise PermissionDenied("You are not authorized to delete events ")


class DayDetails(ListView):
    template_name = 'events/day.html'
    model = Event

    def get_queryset(self, *args, **kwargs):
        selected_day = datetime(year=self.kwargs['year'], month=self.kwargs['month'], day=self.kwargs['day'])
        day_after = selected_day + timedelta(days=1)
        query_set = super().get_queryset().filter(Q(author=self.request.user) | Q(shared=self.request.user),
                                                  start_time__gte=selected_day, start_time__lt=day_after).distinct()
        return query_set

templates/events/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="create-new-event">
        <a onclick="displayModal(CREATE_EVENT_URL)">Novi događaj <i class="fa-solid fa-circle-plus fa-xl"></i></a>
    </div>
    <div class="dk-calendar">
        <div class="dk-create-calendar">
            <div class="year-month-calendar">
                <div class="dk-year-calendar">
                    <h1> {{ year }}</h1>
                </div>
                <div class="up-down-year">
                    <a href="{% url 'specific-month-calendar' previous_year month %}"><i
                            class="fa-solid fa-angle-up"></i></a>
                    <a href="{% url 'specific-month-calendar' next_year month %}"><i class="fa-solid fa-angle-down"></i></a>
                </div>
                <div class="dk-month-calendar">
                    <h1>{{ selected_month }}</h1>
                </div>
                <div class="up-down-month">
                    {% if previous_month != 12 %}
                        <a href="{% url 'specific-month-calendar' year previous_month %}"><i
                                class="fa-solid fa-angle-up"></i></a>
                    {% else %}
                        <a href="{% url 'specific-month-calendar' previous_year previous_month %}"><i
                                class="fa-solid fa-angle-up"></i></a>
                    {% endif %}
                    {% if next_month != 1 %}
                        <a href="{% url 'specific-month-calendar' year next_month %}"><i
                                class="fa-solid fa-angle-down"></i></a>
                    {% else %}
                        <a href="{% url 'specific-month-calendar' next_year next_month %}"><i
                                class="fa-solid fa-angle-down"></i></a>
                    {% endif %}
                </div>
            </div>
            {{ calendar }}
        </div>
    </div>
{% endblock %}

templates/events/day.html
<form class="ov-form">
    <h3 class="ov-form__title">Dnevni pregled<button type="button" id="close-button" class="close-button-event" onclick="modalClose()"><i
            class="fa-solid fa-rectangle-xmark"></i>
    </button></h3>

    {% if event_list %}
        {% for event in event_list %}
            <div class="event-day-item">
                <a onclick="displayModal(EVENT_PREVIEW_URL+{{ event.id }})"><h4
                        class="event-day-item-title">{{ event.title }}</h4></a>
                {% if user.is_admin or user.is_superuser or event.author == request.user %}
                    <div class="ov-form__btn-container">
                        <a class="event-day-list-btn" type="button"
                           onclick="displayModal(EDIT_EVENT_URL+{{ event.id }})"><i
                                class="fa-solid fa-pen-to-square"></i></a>
                        <a class="event-day-list-btn" type="button"
                           onclick="displayModal(DELETE_EVENT_URL+{{ event.id }})"><i class="fa-solid fa-trash-can"></i></a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <h4 class="event-day-no-events">Nema događaja danas.</h4>
    {% endif %}
</form>

templates/events/event-confirm-deletion.html
<form id="delete-event-form" class="ov-form" method="post">
    <h3 class="ov-form__title">Brisanje događajа<button type="button" id="close-button" class="close-button-event" onclick="modalClose()"><i
            class="fa-solid fa-rectangle-xmark"></i>
    </button></h3>

    <div class="ov-delete-modal">
        {% csrf_token %}
        <p class="ov-delete-modal__question">Jeste li sigurni da želite da izbrišete događaj: {{ object.title }}?</p>
        <div class="ov-form__btn-container">
            <button type="button" id="close-button" class="ov-form__btn ov-form__btn--blue" onclick="modalClose()">Ne</button>
            <button type="button" id="submitForm" class="ov-form__btn"
                    onclick="genericSubmitForm('delete-event-form', DELETE_EVENT_URL + {{ object.id }} + '/', DELETE_SUCCESSFUL)">Da
            </button>
        </div>
    </div>
</form>

templates/events/event-edit.html
<form id="create-event-form" class="ov-form" method="post">
    {% csrf_token %}
    <h3 class="ov-form__title">Uređivanje događaja<button type="button" id="close-button" class="close-button-event" onclick="modalClose()"><i
            class="fa-solid fa-rectangle-xmark"></i>
    </button></h3>

    {% for error in form.non_field_errors %}
        <div>
            {{ error }}
        </div>
        {% endfor %}
    <div>
        <label>{{ form.title.label }}</label>

        {{ form.title }}
    </div>
    {% if form.title.errors %}
        <div>
            {{ form.title.errors }}
        </div>
    {% endif %}
    <div>
        <label>{{ form.details.label }}</label>

        {{ form.details }}
    </div>
    <div>
        <label>{{ form.start_time.label }}</label>

        {{ form.start_time }}
    </div>
    {% if form.start_time.errors %}
        <div>
            {{ form.start_time.errors }}
        </div>
    {% endif %}
    <div>
        <label>{{ form.end_time.label }}</label>

        {{ form.end_time }}
    </div>
    <div>
        <label>{{ form.repeat_days.label }}</label>

        {{ form.repeat_days }}
    </div>
    <div>
        <label>{{ form.repeat_every_year.label }}</label>

        {{ form.repeat_every_year }}
    </div>

      <div class="shared-choice-container">
        <label>{{ form.shared.label }}</label>
        <input id="myInput" type="text" onkeyup="filterTextInput()" placeholder="Pretraga...">
        {{ form.shared }}
    </div>
    <button type="button" class="ov-form__btn" onclick="genericSubmitForm('create-event-form', EDIT_EVENT_URL + {{ object.id }} + '/', SUCCESSFUL_ACTION)">Potvrdi</button>
</form>

templates/events/event-preview.html
<form id="edit-event-form" class="ov-form event-form">
    <h3 class="ov-form__title">Detalji događaja<button type="button" id="close-button" class="close-button-event" onclick="modalClose()"><i
            class="fa-solid fa-rectangle-xmark"></i>
    </button></h3>

    <div class="event-form-content">
        <div class="event-form-header">
            <h4>{{ event.title }}</h4>
            {% if event.type == null%}
                <p class="not-visible">
                {% else %}
                <p>{{ event.type }}</p>
            {% endif %}
            <p>{{ event.start_time|date }}</p>
            <p>Od {{ event.start_time|date:'H:i' }}
            do {% if event.end_time %}{{ event.end_time|date:'H:i' }}{% else %} nepoznato vrijeme{% endif %}</p>
            <p>Kreiran {{ event.creation_date.day }}.{{ event.creation_date.month }}.{{ event.creation_date.year }}</p>
        </div>

        <div class="event-preview-form">
            <h4>Bilješke</h4>
            <p>{% if event.details %}{{ event.details }}{% else %}Nema detalja{% endif %}</p>
        </div>
        <div class="ov-form__btn-container">
            {% if user.is_admin or user.is_superuser or event.author == request.user %}
                <button class="ov-form__btn" type="button" onclick="displayModal(EDIT_EVENT_URL+{{ event.id }})">Uredi
                </button>
                <button class="ov-form__btn ov-form__btn--blue" type="button"
                        onclick="displayModal(DELETE_EVENT_URL+{{ event.id }})">Izbriši
                </button>
            {% endif %}

        </div>
    </div>

</form>

templates/events/event.html
<form id="create-event-form" class="ov-form event-form" method="post">
    <h3 class="ov-form__title">Dodavanje događaja<button type="button" id="close-button" class="close-button-event" onclick="modalClose()"><i
            class="fa-solid fa-rectangle-xmark"></i>
    </button></h3>

    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <div>
            {{ error }}
        </div>
    {% endfor %}
    <div>
        <label>{{ form.title.label }}</label>

        {{ form.title }}
    </div>
    {% if form.title.errors %}
        <div>
            {{ form.title.errors }}
        </div>
    {% endif %}
    <div>
        <label>{{ form.details.label }}</label>

        {{ form.details }}
    </div>
    <div>
        <label>{{ form.start_time.label }}</label>

        {{ form.start_time }}
    </div>
    {% if form.start_time.errors %}
        <div>
            {{ form.start_time.errors }}
        </div>
    {% endif %}
    <div>
        <label>{{ form.end_time.label }}</label>

        {{ form.end_time }}
    </div>
    <div>
        <label>{{ form.repeat_days.label }}</label>

        {{ form.repeat_days }}
    </div>
    <div>
        <label>{{ form.repeat_every_year.label }}</label>

        {{ form.repeat_every_year }}
    </div>
    <div>
        <label>{{ form.type.label }}</label>
        {{ form.type }}
    </div>
    <div>
        <div id="shared-choice-container" class="shared-choice-container">
            <label>{{ form.shared.label }}</label>
            <input id="myInput" type="text" onkeyup="filterTextInput()" placeholder="Pretraga...">
            {{ form.shared }}
        </div>
        <div class="ov-form__btn-container">
            <button class="ov-form__btn" type="button"
                    onclick="genericSubmitForm('create-event-form', CREATE_EVENT_URL, SUCCESSFUL_ACTION)">Potvrdi
            </button>
        </div>
    </div>
</form>